## 📐 Dimensiones en NumPy

En **NumPy**, las **dimensiones** (también llamadas *ejes* o *axes*) indican **cuántos niveles de profundidad tiene un array**.  
Un array puede tener una o varias dimensiones:

In [1]:
import numpy as np

# SCALAR

In [2]:
scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


# VECTOR

In [3]:
vector = np.array([1,2,3])
print(vector)
print(f"Nro de dimensiones : {vector.ndim}")

[1 2 3]
Nro de dimensiones : 1


# MATRICES

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print(f"Nro de dimensiones : {matriz.ndim}")

[[1 2 3]
 [4 5 6]]
Nro de dimensiones : 2


# TENSOR - N DIMENSIONES

In [6]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(tensor)
print(f"Nro de dimensiones : {tensor.ndim}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Nro de dimensiones : 3
