# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[6, 1],
       [5, 6],
       [4, 9]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.ndim

2

In [5]:
arr.reshape(1,6)

array([[6, 1, 5, 6, 4, 9]])

# MAX Y ARGMAX

In [6]:
arr = np.random.randint(1,20,10)
arr

array([ 6,  2,  8,  4,  3, 19, 12, 14,  5,  3])

In [7]:
matriz = arr.reshape(2,5)
matriz

array([[ 6,  2,  8,  4,  3],
       [19, 12, 14,  5,  3]])

In [8]:
arr.max()

np.int64(19)

In [9]:
matriz.max()

np.int64(19)

In [10]:
arr.argmax()

np.int64(5)

In [11]:
matriz.argmax()

np.int64(5)

# MIN Y ARGMIN

In [12]:
arr.min()

np.int64(2)

In [13]:
matriz.min()

np.int64(2)

In [14]:
matriz.min(0)

array([6, 2, 8, 4, 3])

In [15]:
matriz.min(1)

array([2, 3])

# SORT

In [16]:
arr

array([ 6,  2,  8,  4,  3, 19, 12, 14,  5,  3])

In [18]:
arr.sort()
arr

array([ 2,  3,  3,  4,  5,  6,  8, 12, 14, 19])

In [21]:
arr2 = arr[::-1]
arr2

array([19, 14, 12,  8,  6,  5,  4,  3,  3,  2])